language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
    - composer install

script: phpunit --coverage-text

services:
    postgresql
    mysql

before_script:
  - composer install
  - psql -c 'create database _unittest_' -U postgres
  - mysql -e 'create database _unittest_'

notifications:
  email:
    - github@crazedsanity.com
